# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-06-18 11:24
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0009_auto_20170617_1245'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oglas',
            name='vlasnik',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
