# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-06-18 11:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0010_auto_20170618_1324'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oglas',
            name='vlasnik',
            field=models.CharField(max_length=200),
        ),
    ]
