# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-18 16:42
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0017_auto_20170618_1403'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oglas',
            name='vlasnik',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
