# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-06-20 06:37
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0018_auto_20170618_1842'),
    ]

    operations = [
        migrations.CreateModel(
            name='Kategorija',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=40, unique=True)),
                ('description', models.TextField()),
            ],
            options={
                'verbose_name_plural': 'Kategorije',
            },
        ),
        migrations.CreateModel(
            name='KategorijaToOglas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kategorija', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='music.Kategorija')),
            ],
        ),
        migrations.AlterModelOptions(
            name='oglas',
            options={'ordering': ['-datum_objave'], 'verbose_name_plural': 'Oglasi'},
        ),
        migrations.AddField(
            model_name='oglas',
            name='datum_objave',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='oglas',
            name='slug',
            field=models.SlugField(default=213, max_length=40, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='kategorijatooglas',
            name='oglas',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='music.Oglas'),
        ),
        migrations.AddField(
            model_name='oglas',
            name='kategorije',
            field=models.ManyToManyField(blank=True, through='music.KategorijaToOglas', to='music.Kategorija'),
        ),
    ]
