# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-06-20 07:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0019_auto_20170620_0837'),
    ]

    operations = [
        migrations.AddField(
            model_name='oglas',
            name='opis',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
