# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-06-20 08:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0020_oglas_opis'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oglas',
            name='opis',
            field=models.TextField(default=''),
        ),
    ]
