# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-06-21 12:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0021_auto_20170620_1002'),
    ]

    operations = [
        migrations.AddField(
            model_name='oglas',
            name='stanje',
            field=models.CharField(choices=[('Korisceno', 'Korisceno'), ('Novo', 'Novo')], default='Novo', max_length=100),
        ),
    ]
