# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-23 13:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0022_oglas_stanje'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='oglas',
            name='kategorije',
        ),
        migrations.AddField(
            model_name='oglas',
            name='kategorija',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='music.Kategorija'),
        ),
    ]
