# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-06-23 19:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0025_auto_20170623_2016'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MyUser',
        ),
    ]
