# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-06-23 20:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0027_employee'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='department',
            new_name='broj',
        ),
    ]
