# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-06-23 21:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0028_auto_20170623_2224'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='broj',
            field=models.CharField(max_length=15, validators=[int]),
        ),
    ]
