# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-06-23 21:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0029_auto_20170623_2311'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='broj',
            field=models.IntegerField(max_length=15),
        ),
    ]
