# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-06-23 21:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0030_auto_20170623_2312'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='lokacija',
            field=models.CharField(default='mrtvibroj', max_length=40),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='employee',
            name='broj',
            field=models.CharField(max_length=15),
        ),
    ]
