# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-29 13:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0035_auto_20170627_2002'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='slika',
            field=models.FileField(default='media/defprofilepic.png', upload_to=''),
        ),
    ]
